# Generated by Django 3.2.13 on 2022-05-28 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('birthDay', models.DateField(default='2000-01-01')),
                ('homeTown', models.CharField(default='Unkown', max_length=100)),
                ('phone', models.CharField(default='Unkown', max_length=20)),
                ('gender', models.IntegerField(choices=[(0, 'Unkown'), (1, 'Female'), (2, 'Male')], default=0)),
                ('educationLevel', models.IntegerField(choices=[(0, 'Unkown'), (1, 'High School'), (2, 'Bachelor')], default=0)),
                ('avatar', models.ImageField(default='unkown.jpg', upload_to='')),
                ('embedding', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='unkown.jpg', upload_to='')),
                ('embedding', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
