# Generated by Django 3.2.13 on 2022-05-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('birthDay', models.DateField(default='2000-01-01')),
                ('homeTown', models.CharField(default='Unkown', max_length=100)),
                ('phone', models.CharField(default='Unkown', max_length=20)),
                ('gender', models.IntegerField(choices=[(0, 'Unkown'), (1, 'Female'), (2, 'Male')], default=0)),
                ('educationLevel', models.CharField(default='Unkown', max_length=100)),
                ('avatar', models.ImageField(default='unkown.jpg', upload_to='')),
                ('embedding', models.BinaryField()),
            ],
        ),
    ]
